code: "cv"
version: "0.1"
title: "Cv"
oneliner: "CV for member to showoff their portfolio and get connected to startup who are looking for talent"
lastUpdate: "2020-10-22"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
