code: "resource"
version: "1.1"
title: "Resource Directory"
oneliner: "Module for ecosystem resources directory"
lastUpdate: "2020-06-22"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
