code: "openHub"
version: "1.2"
title: "OpenHUB"
oneliner: "OpenHUB - the open source ecosystem management tool"
lastUpdate: "2020-05-28"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
