code: "openHub"
version: "1.3"
title: "OpenHUB"
oneliner: "OpenHUB - the open source ecosystem management tool"
lastUpdate: "2020-05-28"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
dependency:
  - module: 'interest'
    version: '1.0'