code: "f7"
version: "1.5"
title: "Form 7"
oneliner: "A module to allow custom forms to be easily created"
lastUpdate: "2020-03-12"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
contributors:
  - author: "Mahboubian"
    organization: "MaGIC"
    email: "mahboubian@mymagic.my"