code: "esLog"
version: "1.0"
title: "Elastic Search Log"
oneliner: "Added log functionality on commmon services using Elastic Search"
lastUpdate: "2020-03-12"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
