code: "eventbrite"
version: "1.2"
title: "Eventbrite"
oneliner: "Integration with Eventbrite services"
lastUpdate: "2020-04-07"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
  dependency:
    - module: 'bumi'
      version: '1.0'