code: "boilerplateStart"
version: "1.1"
title: "Boilerplate Start"
oneliner: "Serve as a template for new module to guide developer"
lastUpdate: "2020-03-12"
developer:
  author: "Tan Yee Siang"
  organization: "MaGIC"
  email: "yee.siang@mymagic.my"
