code: "interest"
version: "1.2"
title: "Interest"
oneliner: "Manage members interest to provide recommendation"
lastUpdate: "2020-03-25"
developer:
  author: "Rosaan Ramasamy"
  organization: "MaGIC"
  email: "rosaan@mymagic.my"